spring:
  thymeleaf:
    prefix: classpath:/templates
#    prefix: classpath:/static/html/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    cache-period: 0
    template:
      cache: false