spring:
  session:
    store-type: redis
  redis:
    database: 0
    host: 192.168.0.63
    port: 6379
    password:
    timeout: 300
    maxIdle: 8
    minIdle: 0
    maxActive: 8
    maxWait: -1
#    sentinel:
#      master: name of Redis server
#      nodes: comma-separated list of host:port pairs